#ifndef famstrings_h
#define famstrings_h

#define langcount 1
extern char *languages[];

extern char *languagenames[];

extern char msg_nomsg[];
#define MAX_nomsg 43
extern char msg_ok[];
#define MAX_ok 3
extern char msg_cancel[];
#define MAX_cancel 8
extern char msg_apply[];
#define MAX_apply 10
extern char msg_save[];
#define MAX_save 7
extern char msg_clear[];
#define MAX_clear 8
extern char msg_restore[];
#define MAX_restore 20
extern char msg_revert[];
#define MAX_revert 10
extern char msg_saveto[];
#define MAX_saveto 20
extern char msg_oksave[];
#define MAX_oksave 22
extern char msg_window_title[];
#define MAX_window_title 10
extern char msg_in[];
#define MAX_in 3
extern char msg_untitled[];
#define MAX_untitled 9
extern char msg_notes_title[];
#define MAX_notes_title 10
extern char msg_unnamed[];
#define MAX_unnamed 10
extern char msg_nullindi[];
#define MAX_nullindi 7
extern char msg_info_title[];
#define MAX_info_title 29
extern char msg_menu_file[];
#define MAX_menu_file 8
extern char msg_menu_load[];
#define MAX_menu_load 7
extern char msg_menu_save[];
#define MAX_menu_save 7
extern char msg_menu_saveas[];
#define MAX_menu_saveas 17
extern char msg_menu_print[];
#define MAX_menu_print 9
extern char msg_menu_newview[];
#define MAX_menu_newview 13
extern char msg_menu_discard[];
#define MAX_menu_discard 11
extern char msg_menu_stats[];
#define MAX_menu_stats 13
extern char msg_menu_quit[];
#define MAX_menu_quit 8
extern char msg_menu_folk[];
#define MAX_menu_folk 10
extern char msg_menu_add[];
#define MAX_menu_add 12
extern char msg_menu_goto[];
#define MAX_menu_goto 13
extern char msg_menu_reports[];
#define MAX_menu_reports 9
extern char msg_menu_repstd[];
#define MAX_menu_repstd 9
extern char msg_menu_repfam[];
#define MAX_menu_repfam 14
extern char msg_menu_repweb[];
#define MAX_menu_repweb 20
extern char msg_menu_settings[];
#define MAX_menu_settings 14
extern char msg_menu_lang[];
#define MAX_menu_lang 9
extern char msg_menu_choices[];
#define MAX_menu_choices 12
extern char msg_menu_savech[];
#define MAX_menu_savech 13
extern char msg_help[];
#define MAX_help 5
extern char msg_menu_intro[];
#define MAX_menu_intro 13
extern char msg_menu_mainUI[];
#define MAX_menu_mainUI 12
extern char msg_menu_indiUI[];
#define MAX_menu_indiUI 12
extern char msg_menu_famUI[];
#define MAX_menu_famUI 19
extern char msg_menu_findUI[];
#define MAX_menu_findUI 21
extern char msg_menu_prefUI[];
#define MAX_menu_prefUI 13
extern char msg_menu_GEDCOM[];
#define MAX_menu_GEDCOM 16
extern char msg_menu_about[];
#define MAX_menu_about 6
extern char msg_menu_edit[];
#define MAX_menu_edit 9
extern char msg_menu_notes[];
#define MAX_menu_notes 11
extern char msg_menu_marry[];
#define MAX_menu_marry 7
extern char msg_menu_younger[];
#define MAX_menu_younger 11
extern char msg_menu_later[];
#define MAX_menu_later 10
extern char msg_menu_child[];
#define MAX_menu_child 28
extern char msg_menu_newfam[];
#define MAX_menu_newfam 29
extern char msg_menu_remove[];
#define MAX_menu_remove 8
extern char msg_menu_unmarry[];
#define MAX_menu_unmarry 16
extern char msg_menu_indreps[];
#define MAX_menu_indreps 9
extern char msg_menu_ancs[];
#define MAX_menu_ancs 10
extern char msg_menu_savescr[];
#define MAX_menu_savescr 23
extern char msg_info_name[];
#define MAX_info_name 5
extern char msg_info_author[];
#define MAX_info_author 7
extern char msg_info_version[];
#define MAX_info_version 8
extern char msg_info_purpose[];
#define MAX_info_purpose 8
extern char msg_appname[];
#define MAX_appname 10
extern char msg_author[];
#define MAX_author 26
extern char msg_version[];
#define MAX_version 30
extern char msg_purpose[];
#define MAX_purpose 34
extern char msg_calendar[];
#define MAX_calendar 11
extern char msg_gregorian[];
#define MAX_gregorian 12
extern char msg_julian[];
#define MAX_julian 7
extern char msg_default[];
#define MAX_default 8
extern char msg_indi_title[];
#define MAX_indi_title 19
extern char msg_fam_title[];
#define MAX_fam_title 34
extern char msg_anonymous[];
#define MAX_anonymous 10
extern char msg_newperson[];
#define MAX_newperson 20
extern char msg_name[];
#define MAX_name 5
extern char msg_title[];
#define MAX_title 6
extern char msg_event_date[];
#define MAX_event_date 5
extern char msg_event_time[];
#define MAX_event_time 6
extern char msg_event_age[];
#define MAX_event_age 4
extern char msg_event_place[];
#define MAX_event_place 6
extern char msg_event_site[];
#define MAX_event_site 5
extern char msg_event_plot[];
#define MAX_event_plot 5
extern char msg_event_cause[];
#define MAX_event_cause 6
extern char msg_event_src[];
#define MAX_event_src 8
extern char msg_event_ident[];
#define MAX_event_ident 12
extern char msg_birth[];
#define MAX_birth 10
extern char msg_chr[];
#define MAX_chr 18
extern char msg_bapm[];
#define MAX_bapm 9
extern char msg_death[];
#define MAX_death 6
extern char msg_crem[];
#define MAX_crem 11
extern char msg_buri[];
#define MAX_buri 12
extern char msg_gender[];
#define MAX_gender 7
extern char msg_male[];
#define MAX_male 6
extern char msg_female[];
#define MAX_female 8
extern char msg_unknown[];
#define MAX_unknown 8
extern char msg_living[];
#define MAX_living 7
extern char msg_indi_ma[];
#define MAX_indi_ma 7
extern char msg_indi_pa[];
#define MAX_indi_pa 7
extern char msg_husband[];
#define MAX_husband 8
extern char msg_wife[];
#define MAX_wife 6
extern char msg_engage[];
#define MAX_engage 11
extern char msg_marry[];
#define MAX_marry 9
extern char msg_divorce[];
#define MAX_divorce 8
extern char msg_notes[];
#define MAX_notes 11
extern char msg_sources[];
#define MAX_sources 8
extern char msg_will[];
#define MAX_will 10
extern char msg_probate[];
#define MAX_probate 13
extern char msg_newfamily[];
#define MAX_newfamily 19
extern char msg_find_title[];
#define MAX_find_title 33
extern char msg_find[];
#define MAX_find 10
extern char msg_completions_title[];
#define MAX_completions_title 24
extern char msg_stats_title[];
#define MAX_stats_title 23
extern char msg_stats_file[];
#define MAX_stats_file 19
extern char msg_stats_indis[];
#define MAX_stats_indis 13
extern char msg_stats_max_indi[];
#define MAX_stats_max_indi 17
extern char msg_stats_fams[];
#define MAX_stats_fams 10
extern char msg_stats_maxfam[];
#define MAX_stats_maxfam 16
extern char msg_stats_srcs[];
#define MAX_stats_srcs 22
extern char msg_stats_max_src[];
#define MAX_stats_max_src 17
extern char msg_stats_repos[];
#define MAX_stats_repos 27
extern char msg_stats_max_repo[];
#define MAX_stats_max_repo 17
extern char msg_prefs_title[];
#define MAX_prefs_title 24
extern char msg_prefs_names[];
#define MAX_prefs_names 6
extern char msg_prefs_famnames[];
#define MAX_prefs_famnames 30
extern char msg_prefs_titles[];
#define MAX_prefs_titles 15
extern char msg_prefs_dates[];
#define MAX_prefs_dates 16
extern char msg_prefs_treedates[];
#define MAX_prefs_treedates 24
extern char msg_prefs_including[];
#define MAX_prefs_including 14
extern char msg_prefs_spousedates[];
#define MAX_prefs_spousedates 23
extern char msg_prefs_marrydates[];
#define MAX_prefs_marrydates 19
extern char msg_prefs_yearonly[];
#define MAX_prefs_yearonly 25
extern char msg_prefs_dateformat[];
#define MAX_prefs_dateformat 21
extern char msg_prefs_gedcom[];
#define MAX_prefs_gedcom 13
extern char msg_prefs_iso[];
#define MAX_prefs_iso 15
extern char msg_prefs_misc[];
#define MAX_prefs_misc 17
extern char msg_prefs_xref[];
#define MAX_prefs_xref 21
extern char msg_prefs_xrefquit[];
#define MAX_prefs_xrefquit 13
extern char msg_prefs_xrefwarn[];
#define MAX_prefs_xrefwarn 15
extern char msg_prefs_xrefignore[];
#define MAX_prefs_xrefignore 18
extern char msg_prefs_repdates[];
#define MAX_prefs_repdates 31
extern char msg_prefs_repgedcom[];
#define MAX_prefs_repgedcom 7
extern char msg_prefs_repiso[];
#define MAX_prefs_repiso 9
extern char msg_prefs_replocal[];
#define MAX_prefs_replocal 10
extern char msg_prefs_repother[];
#define MAX_prefs_repother 7
extern char msg_gpl_box[];
#define MAX_gpl_box 960
#define MSG_BUFLEN 961
#endif
